use crate::world::grid::Position;
use crate::components::robot::RobotId;

/// Type-safe order identifier.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct OrderId(pub u32);

/// The lifecycle stage of an order.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum OrderStatus {
    Pending,
    InProgress,
    Completed,
}

/// A single warehouse order
#[derive(Debug, Clone)]
pub struct Order {
    pub id:               OrderId,
    /// The shelf tile the robot must reach to collect the item
    pub pickup_location:  Position,
    /// Tick this order was generated by the Poisson process
    pub created_at_tick:  u64,
    /// Tick this order was delivered (set on completion)
    pub completed_at_tick: Option<u64>,
    pub status:           OrderStatus,
    /// Which robot is currently responsible for this order
    pub assigned_to:      Option<RobotId>,
}

impl Order {
    pub fn new(id: OrderId, pickup_location: Position, created_at_tick: u64) -> Self {
        Order {
            id,
            pickup_location,
            created_at_tick,
            completed_at_tick: None,
            status:            OrderStatus::Pending,
            assigned_to:       None,
        }
    }

    /// Ticks elapsed between order creation and delivery. None if not yet complete.
    pub fn fulfillment_time(&self) -> Option<u64> {
        self.completed_at_tick.map(|t| t - self.created_at_tick)
    }
}