//Debug File Generated by Claude
use std::collections::HashMap;
use crate::components::robot::{RobotId, RobotState};
use crate::world::World;
use crate::world::grid::{Position, TileKind};

// ─────────────────────────────────────────────────────────────────────────────
// Public API — call either or both from simulation.rs
// ─────────────────────────────────────────────────────────────────────────────

/// Prints a full-world ASCII map with robot positions overlaid, then the
/// legend. All output goes to stdout.
pub fn print_grid(world: &World) {
    let robot_positions: HashMap<Position, RobotId> = world.robots
        .values()
        .map(|r| (r.position, r.id))
        .collect();

    // Header row: column indices
    print!("     ");
    for x in 0..world.grid.width {
        print!("{:<2}", x % 10); // keep it compact for wide grids
    }
    println!();

    print!("   +-");
    for _ in 0..world.grid.width {
        print!("--");
    }
    println!("+");

    for y in 0..world.grid.height {
        print!("{:>2} | ", y);

        for x in 0..world.grid.width {
            let pos = Position::new(x, y);

            if let Some(&robot_id) = robot_positions.get(&pos) {
                // Show robot ID. Uppercase = carrying payload.
                let robot = &world.robots[&robot_id];
                let label = format!("{}", robot_id.0);
                if robot.is_carrying_payload {
                    print!("\x1b[1;33m{} \x1b[0m", label); // bold yellow
                } else {
                    print!("\x1b[1;36m{} \x1b[0m", label); // bold cyan
                }
            } else {
                let symbol = match world.grid.get(pos) {
                    TileKind::Floor          => ". ",
                    TileKind::Wall           => "\x1b[90m##\x1b[0m",     // dark gray
                    TileKind::ShelfLocation  => "\x1b[32ms \x1b[0m",     // green
                    TileKind::ChargingStation=> "\x1b[35mC \x1b[0m",     // magenta
                    TileKind::DispatchZone   => "\x1b[1;34mD \x1b[0m",   // bold blue
                };
                print!("{}", symbol);
            }
        }
        println!("|");
    }

    print!("   +-");
    for _ in 0..world.grid.width {
        print!("--");
    }
    println!("+");

    // Legend
    println!(
        "   Legend:  . floor  \x1b[90m##\x1b[0m wall  \x1b[32ms\x1b[0m shelf  \
         \x1b[35mC\x1b[0m charger  \x1b[1;34mD\x1b[0m dispatch  \
         \x1b[1;36m0\x1b[0m robot (empty)  \x1b[1;33m0\x1b[0m robot (carrying)"
    );
}

/// Prints a detailed text status of every robot and every charging station.
/// Robots with suspicious state (e.g. routing but no path) are flagged with
/// warning symbols to help identify what's causing the freeze.
pub fn print_status(world: &World) {
    println!("{}", separator("ROBOTS"));

    // Sort by robot ID for consistent output
    let mut robot_ids: Vec<RobotId> = world.robots.keys().copied().collect();
    robot_ids.sort_by_key(|id| id.0);

    for id in &robot_ids {
        let robot = &world.robots[id];

        let state_str = match &robot.state {
            RobotState::Idle                        => "Idle".to_string(),
            RobotState::RoutingToPickup  { order_id }  => format!("RoutingToPickup(Order#{})",  order_id.0),
            RobotState::RoutingToDropoff { order_id }  => format!("RoutingToDropoff(Order#{})", order_id.0),
            RobotState::RoutingToCharge  { station_id }=> format!("RoutingToCharge(Stn#{})",    station_id.0),
            RobotState::WaitingToCharge  { station_id }=> format!("WaitingToCharge(Stn#{})",    station_id.0),
            RobotState::Charging         { station_id }=> format!("Charging(Stn#{})",           station_id.0),
        };

        let dest_str = match robot.destination {
            Some(pos) => format!("({},{})", pos.x, pos.y),
            None      => "--".to_string(),
        };

        let path_str = if robot.planned_path.is_empty() {
            "--".to_string()
        } else {
            format!("{} steps", robot.planned_path.len())
        };

        let batt_bar = battery_bar(robot.battery_level, 100.0); // assumes 100 max; close enough for display

        // Warning flags — these are what you want to look at when things freeze
        let mut flags: Vec<&str> = Vec::new();

        if robot.is_routing() && robot.planned_path.is_empty() && robot.destination.is_some() {
            // The most common freeze cause: A* returned None (no path found),
            // so the robot is stuck in a routing state with nothing to do.
            flags.push("⚠ NO PATH FOUND");
        }
        if robot.is_routing() && robot.destination.is_none() {
            // Routing with no destination set — state machine inconsistency.
            flags.push("⚠ ROUTING BUT NO DESTINATION");
        }
        if matches!(robot.state, RobotState::WaitingToCharge { .. }) {
            // Robot is sitting in a charge queue — not stuck, but worth knowing.
            flags.push("(in charge queue)");
        }

        let flag_str = if flags.is_empty() {
            String::new()
        } else {
            format!("  \x1b[33m{}\x1b[0m", flags.join("  "))
        };

        println!(
            "  Robot {:>2}  pos:({:>2},{:>2})  {:<34}  batt:[{}]  dest:{:<8}  path:{}{}",
            id.0,
            robot.position.x,
            robot.position.y,
            state_str,
            batt_bar,
            dest_str,
            path_str,
            flag_str,
        );
    }

    println!();
    println!("{}", separator("CHARGING STATIONS"));

    let mut station_ids: Vec<_> = world.stations.keys().copied().collect();
    station_ids.sort_by_key(|id| id.0);

    for id in &station_ids {
        let station = &world.stations[id];

        let charging_str = match station.charging_robot {
            Some(rid) => {
                let batt = world.robots[&rid].battery_level;
                format!("Robot#{} ({:.1}/100.0)", rid.0, batt)
            }
            None => "empty".to_string(),
        };

        let queue_str = if station.queue.is_empty() {
            "[]".to_string()
        } else {
            let ids: Vec<String> = station.queue.iter().map(|r| format!("Robot#{}", r.0)).collect();
            format!("[{}]", ids.join(", "))
        };

        println!(
            "  Station {}  pos:({},{})  charging:{:<28}  queue:{}",
            id.0,
            station.position.x,
            station.position.y,
            charging_str,
            queue_str,
        );
    }

    println!();
    println!("{}", separator("ORDER COUNTS"));
    println!(
        "  pending: {}   active: {}   completed: {}",
        world.pending_orders.len(),
        world.active_orders.len(),
        world.completed_orders.len(),
    );
}

/// Runs a quick scan and returns true if any robot looks frozen.
/// Use this to trigger an automatic debug dump rather than waiting for
/// a periodic print interval.
///
/// A robot is considered frozen if it is in a routing state but has an
/// empty planned_path and a set destination — meaning A* returned None
/// and the robot has nowhere to go.
pub fn has_stuck_robots(world: &World) -> bool {
    world.robots.values().any(|r| {
        r.is_routing() && r.destination.is_some() && r.planned_path.is_empty()
    })
}

// ─────────────────────────────────────────────────────────────────────────────
// Private helpers
// ─────────────────────────────────────────────────────────────────────────────

/// A 10-character ASCII battery bar, e.g. [████████░░]
fn battery_bar(current: f64, max: f64) -> String {
    let filled = ((current / max) * 10.0).round() as usize;
    let filled  = filled.min(10);
    let empty   = 10 - filled;
    let bar: String = "█".repeat(filled) + &"░".repeat(empty);
    let color = if current / max < 0.25 {
        "\x1b[31m" // red when low
    } else if current / max < 0.5 {
        "\x1b[33m" // yellow when medium
    } else {
        "\x1b[32m" // green when good
    };
    format!("{}{}\x1b[0m", color, bar)
}

fn separator(label: &str) -> String {
    let prefix = "─".repeat(4);
    let suffix = "─".repeat(54usize.saturating_sub(label.len().min(50)));
    format!("  {} {} {}", prefix, label, suffix)
}
